@php
    $totalQuantity = $deliveryOrder->items->sum(fn ($item) => (float) $item->quantity);
    $weights = $deliveryOrder->items->pluck('weight')->filter(fn ($weight) => ! is_null($weight));
    $totalWeight = $weights->isNotEmpty() ? $weights->sum(fn ($weight) => (float) $weight) : null;
    $number = fn ($value) => rtrim(rtrim(number_format((float) $value, 4, '.', ''), '0'), '.');
@endphp
<div class="do-page {{ ($pageBreak ?? false) ? 'do-page-break' : '' }}">
    <table class="do-header" role="presentation"><tr><td class="do-brand">@if($logoDataUri ?? null)<img src="{{ $logoDataUri }}" alt="Logo perusahaan">@else<strong>{{ $company['name'] }}</strong>@endif</td><td class="do-title"><h1>DELIVERY ORDER</h1><strong>DELIVERY NO</strong><span>{{ $deliveryOrder->number }}</span><strong>DATE</strong><span>{{ $deliveryOrder->delivery_date->translatedFormat('d F Y') }}</span></td></tr></table>
    <table class="do-addresses" role="presentation"><tr><td><span>TO.</span><strong>{{ $deliveryOrder->to_company }}</strong>@if($deliveryOrder->to_project_site)<strong>{{ $deliveryOrder->to_project_site }}</strong>@endif<div>{!! nl2br(e($deliveryOrder->to_address)) !!}</div></td><td><span>SHIP TO.</span><strong>{{ $deliveryOrder->ship_to_company }}</strong>@if($deliveryOrder->ship_to_project_site)<strong>{{ $deliveryOrder->ship_to_project_site }}</strong>@endif<div>{!! nl2br(e($deliveryOrder->ship_to_address)) !!}</div></td></tr></table>
    <table class="do-shipping" role="presentation"><thead><tr><th>PO NUMBER</th><th>FOB</th><th>PACKAGES</th><th>SHIP VIA</th><th>SHIPMENT</th></tr></thead><tbody><tr><td>{{ $deliveryOrder->purchase_order_no }}</td><td>{{ $deliveryOrder->fob }}</td><td>{{ $deliveryOrder->packages }}</td><td>{{ $deliveryOrder->ship_via }}</td><td>{{ $deliveryOrder->shipment }}</td></tr></tbody></table>
    <table class="do-items"><colgroup><col class="no"><col class="item"><col class="waf"><col class="customer"><col class="qty"><col class="unit"><col class="weight"></colgroup><thead><tr><th>NO</th><th>ITEM NAME</th><th>WAF PART NO</th><th>CUST PARTS NO</th><th>QTY</th><th>UNIT</th><th>WEIGHT</th></tr></thead><tbody>@foreach($deliveryOrder->items as $item)<tr><td>{{ $item->line_number }}</td><td>{{ $item->item_name }}</td><td>{{ $item->waf_part_no }}</td><td>{{ $item->customer_part_no }}</td><td>{{ $number($item->quantity) }}</td><td>{{ $item->unit }}</td><td>{{ is_null($item->weight) ? '' : $number($item->weight) }}</td></tr>@endforeach</tbody></table>
    <table class="do-bottom" role="presentation"><tr><td class="do-description"><strong>DESCRIPTION</strong><div>{!! nl2br(e($deliveryOrder->description)) !!}</div></td><td class="do-totals"><table><tr><th>TOTAL QTY</th><td>{{ $number($totalQuantity) }}</td></tr><tr><th>TOTAL WEIGHT</th><td>{{ is_null($totalWeight) ? '' : $number($totalWeight) }}</td></tr><tr><th>TOTAL ITEM</th><td>{{ $deliveryOrder->items->count() }}</td></tr></table></td></tr></table>
    <table class="do-signatures" role="presentation"><tr><td><strong>APPROVED BY</strong><span></span></td><td><strong>PREPARED BY</strong><span></span></td><td><strong>RECEIVED BY</strong><span></span></td></tr></table>
</div>
