@extends('layouts.app')

@section('title', $deliveryOrder->exists ? 'Edit Delivery Order' : 'Buat Delivery Order')
@section('eyebrow', 'PENGIRIMAN')
@section('heading', $deliveryOrder->exists ? 'Edit Delivery Order' : 'Buat Delivery Order')

@section('content')
@php
    $existingItems = old('items', $deliveryOrder->exists ? $deliveryOrder->items->map(fn ($item) => ['product_id' => $item->product_id, 'quantity' => $item->quantity, 'unit' => $item->unit, 'weight' => $item->weight])->all() : [['product_id' => '', 'quantity' => '', 'unit' => '', 'weight' => '']]);
@endphp
<div class="builder-layout delivery-builder">
<form method="POST" action="{{ $deliveryOrder->exists ? route('delivery-orders.update', $deliveryOrder) : route('delivery-orders.store') }}" class="builder-form delivery-order-form" data-delivery-order-form>
    @csrf @if($deliveryOrder->exists) @method('PUT') @endif
    <div class="builder-intro"><span class="live-dot"></span><div><h2>{{ $deliveryOrder->exists ? 'Edit data, lalu cetak ulang.' : 'Satu form, DO langsung jadi.' }}</h2><p>Pilih pelanggan dan part, isi Qty serta PO, lalu simpan atau buka PDF.</p></div></div>
    @if($errors->any())<div class="error-box"><strong>DO belum dapat disimpan:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <section class="form-step"><div class="step-heading"><span>01</span><div><p class="eyebrow">PELANGGAN</p><h3>Tujuan dan penerima</h3></div></div><div class="form-grid">
        <div class="field"><label for="toPartner">To <b>*</b></label><select id="toPartner" name="to_partner_id" required><option value="">Pilih customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" data-address="{{ $customer->address }}" data-phone="{{ $customer->phone }}" @selected((string) old('to_partner_id', $deliveryOrder->to_partner_id) === (string) $customer->id)>{{ $customer->code }} — {{ $customer->name }}</option>@endforeach<option value="__add_customer__">＋ Tambah customer…</option></select><button class="text-button" type="button" data-add-customer data-customer-target="#toPartner">＋ Tambah customer</button></div>
        <div class="field"><label for="toProject">Project / Department / Site</label><input id="toProject" name="to_project_site" value="{{ old('to_project_site', $deliveryOrder->to_project_site) }}"></div>
        <div class="field field-span-2"><label for="toAddress">Alamat To <b>*</b></label><textarea id="toAddress" name="to_address" rows="3" required>{{ old('to_address', $deliveryOrder->to_address) }}</textarea></div>
        <div class="field field-span-2"><label><input type="checkbox" id="sameDeliveryCustomer"> Penerima sama dengan pelanggan tujuan</label></div>
        <div class="field"><label for="shipToPartner">Ship To <b>*</b></label><select id="shipToPartner" name="ship_to_partner_id" required><option value="">Pilih penerima</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" data-address="{{ $customer->address }}" data-phone="{{ $customer->phone }}" @selected((string) old('ship_to_partner_id', $deliveryOrder->ship_to_partner_id) === (string) $customer->id)>{{ $customer->code }} — {{ $customer->name }}</option>@endforeach<option value="__add_customer__">＋ Tambah customer…</option></select><button class="text-button" type="button" data-add-customer data-customer-target="#shipToPartner">＋ Tambah customer</button></div>
        <div class="field"><label for="shipToProject">Project / Department / Site</label><input id="shipToProject" name="ship_to_project_site" value="{{ old('ship_to_project_site', $deliveryOrder->ship_to_project_site) }}"></div>
        <div class="field field-span-2"><label for="shipToAddress">Alamat Ship To <b>*</b></label><textarea id="shipToAddress" name="ship_to_address" rows="3" required>{{ old('ship_to_address', $deliveryOrder->ship_to_address) }}</textarea></div>
        <div class="field"><label for="shipToPhone">Phone</label><input id="shipToPhone" name="ship_to_phone" value="{{ old('ship_to_phone', $deliveryOrder->ship_to_phone) }}"></div>
    </div></section>

    <section class="form-step"><div class="step-heading"><span>02</span><div><p class="eyebrow">MASTER DATA</p><h3>Pilih part dan isi Qty</h3></div></div><div id="deliveryOrderItems" class="delivery-item-list"></div><button class="button button-ghost" type="button" id="addDeliveryOrderItem">＋ Tambah part</button></section>
    <section class="form-step"><div class="step-heading"><span>03</span><div><p class="eyebrow">DATA PENGIRIMAN</p><h3>Lengkapi informasi DO</h3></div></div><div class="form-grid">
        <div class="field"><label for="deliveryDate">Tanggal DO <b>*</b></label><input type="date" id="deliveryDate" name="delivery_date" value="{{ old('delivery_date', optional($deliveryOrder->delivery_date)->format('Y-m-d')) }}" required></div>
        <div class="field"><label for="purchaseOrderNo">P.O number</label><input id="purchaseOrderNo" name="purchase_order_no" maxlength="100" value="{{ old('purchase_order_no', $deliveryOrder->purchase_order_no) }}" placeholder="Isi nomor PO"></div>
        <div class="field field-span-2"><label for="description">Description / catatan</label><textarea id="description" name="description" rows="3" maxlength="2000">{{ old('description', $deliveryOrder->description) }}</textarea></div>
    </div>
    <details class="delivery-options" @if(collect(['fob', 'packages', 'ship_via', 'shipment'])->contains(fn ($field) => filled(old($field, $deliveryOrder->{$field})))) open @endif><summary>Detail pengiriman lainnya (opsional)</summary><div class="form-grid">
        <div class="field"><label for="fob">FOB</label><input id="fob" name="fob" maxlength="100" value="{{ old('fob', $deliveryOrder->fob) }}"></div>
        <div class="field"><label for="packages">Packages</label><input id="packages" name="packages" maxlength="100" value="{{ old('packages', $deliveryOrder->packages) }}"></div>
        <div class="field"><label for="shipVia">Ship Via</label><input id="shipVia" name="ship_via" maxlength="100" value="{{ old('ship_via', $deliveryOrder->ship_via) }}"></div>
        <div class="field"><label for="shipment">Shipment</label><input id="shipment" name="shipment" maxlength="100" value="{{ old('shipment', $deliveryOrder->shipment) }}"></div>
    </div></details></section>
    <div class="builder-actions"><a class="button button-ghost" href="{{ $deliveryOrder->exists ? route('delivery-orders.show', $deliveryOrder) : route('delivery-orders.index') }}">Batal</a><button class="button button-ghost" type="submit">Simpan DO</button>@if(auth()->user()->canAccess('delivery_orders.print'))<button class="button button-primary" type="submit" name="action" value="print">▣ Simpan & buka PDF</button>@endif</div>
    <p class="secure-note">{{ $deliveryOrder->exists ? 'Nomor DO tetap sama setelah diedit.' : 'Nomor DO dibuat otomatis saat disimpan.' }} Data tersimpan dan dapat diedit atau dicetak ulang.</p>
</form>
<aside class="preview-card delivery-preview"><div class="preview-heading"><div><p class="eyebrow">RINGKASAN</p><h3>Delivery Order</h3></div><span>A4</span></div><p class="delivery-preview-number">{{ $deliveryOrder->exists ? $deliveryOrder->number : 'Nomor DO otomatis' }}</p><dl class="delivery-preview-details"><div><dt>Pelanggan tujuan</dt><dd data-do-preview="to">-</dd></div><div><dt>Penerima</dt><dd data-do-preview="ship">-</dd></div><div><dt>Alamat penerima</dt><dd data-do-preview="address">-</dd></div><div><dt>Tanggal DO</dt><dd data-do-preview="date">-</dd></div><div><dt>Nomor PO</dt><dd data-do-preview="po">-</dd></div></dl><ul class="delivery-preview-items" id="deliveryOrderPreviewItems"></ul><p class="print-hint">Setelah disimpan, buka PDF untuk melihat dan mencetak dokumen A4. Pilih skala <strong>100% / Actual size</strong>.</p></aside>
</div>
<dialog class="customer-dialog" id="customerDialog"><form id="customerForm" method="dialog" data-customer-store-url="{{ route('delivery-orders.customers.store') }}"><div class="panel-heading"><div><p class="eyebrow">CUSTOMER BARU</p><h3>Tambah customer</h3></div><button class="icon-link" type="button" id="closeCustomerDialog" aria-label="Tutup">×</button></div><div class="form-grid"><div class="field field-span-2"><label for="customerName">Nama customer <b>*</b></label><input id="customerName" name="name" maxlength="160" required></div><div class="field field-span-2"><label for="customerAddress">Alamat</label><textarea id="customerAddress" name="address" rows="3" maxlength="2000"></textarea></div><div class="field"><label for="customerPhone">Phone</label><input id="customerPhone" name="phone" maxlength="40"></div></div><p class="field-error" id="customerFormError" hidden></p><div class="bulk-actionbar"><button class="button button-ghost" type="button" id="cancelCustomerDialog">Batal</button><button class="button button-primary" type="submit">Simpan customer</button></div></form></dialog>
<template id="deliveryOrderItemTemplate"><div class="delivery-item" data-delivery-item><div class="delivery-item-heading"><strong data-item-heading>Part</strong><button class="text-button" type="button" data-remove-item>Hapus part</button></div><div class="field"><label for="doProductSearch__INDEX__">Cari part <b>*</b></label><div class="product-picker"><span class="search-icon">⌕</span><input id="doProductSearch__INDEX__" type="search" data-product-search autocomplete="off" placeholder="Cari nama part, WAF part no., customer part, atau kode..." required><div class="product-results" data-product-results></div></div><input type="hidden" data-product name="items[__INDEX__][product_id]"></div><dl class="delivery-part-details"><div><dt>WAF Part No</dt><dd data-waf>-</dd></div><div><dt>Cust Parts No</dt><dd data-customer-part>-</dd></div><div><dt>Catalog</dt><dd data-catalog>-</dd></div></dl><div class="form-grid"><div class="field"><label for="doQuantity__INDEX__">Qty <b>*</b></label><input id="doQuantity__INDEX__" type="number" name="items[__INDEX__][quantity]" min="0.0001" max="99999999" step="0.0001" placeholder="Isi Qty" required></div><div class="field"><label for="doUnit__INDEX__">Satuan <b>*</b></label><input id="doUnit__INDEX__" data-unit name="items[__INDEX__][unit]" maxlength="20" required></div><div class="field"><label for="doWeight__INDEX__">Weight (opsional)</label><input id="doWeight__INDEX__" type="number" name="items[__INDEX__][weight]" min="0" max="99999999" step="0.0001"></div></div></div></template>
<script type="application/json" id="deliveryOrderProducts">@json($products)</script><script type="application/json" id="deliveryOrderInitialItems">@json($existingItems)</script>
@endsection
