@extends('layouts.app')

@section('title', $deliveryOrder->number)
@section('eyebrow', 'DELIVERY ORDER')
@section('heading', $deliveryOrder->number)

@section('content')
<div class="label-result-layout"><section class="panel delivery-summary"><div class="panel-heading"><div><p class="eyebrow">{{ $deliveryOrder->delivery_date->translatedFormat('d F Y') }}</p><h3>{{ $deliveryOrder->to_company }}</h3></div><span class="status draft">{{ $deliveryOrder->items->count() }} item</span></div><div class="stock-form-body"><dl class="delivery-detail-list"><div><dt>Ship To</dt><dd>{{ $deliveryOrder->ship_to_company }}<br>{{ $deliveryOrder->ship_to_address }}</dd></div><div><dt>PO Number</dt><dd>{{ $deliveryOrder->purchase_order_no ?: '-' }}</dd></div><div><dt>Shipment</dt><dd>{{ $deliveryOrder->shipment ?: '-' }}</dd></div></dl><div class="table-wrap"><table class="bulk-table"><thead><tr><th>No</th><th>Item</th><th>WAF Part No</th><th>Cust Parts No</th><th>Qty</th><th>Unit</th><th>Weight</th></tr></thead><tbody>@foreach($deliveryOrder->items as $item)<tr><td>{{ $item->line_number }}</td><td>{{ $item->item_name }}</td><td class="mono">{{ $item->waf_part_no }}</td><td class="mono">{{ $item->customer_part_no ?: '-' }}</td><td>{{ rtrim(rtrim(number_format((float) $item->quantity, 4, '.', ''), '0'), '.') }}</td><td>{{ $item->unit }}</td><td>{{ is_null($item->weight) ? '-' : rtrim(rtrim(number_format((float) $item->weight, 4, '.', ''), '0'), '.') }}</td></tr>@endforeach</tbody></table></div></div></section>
<aside class="result-sidebar"><p class="eyebrow">OUTPUT CETAK</p><h2>DO siap dicetak.</h2><p>PDF DO A4 dan sticker 150 × 100 mm dipisahkan agar ukuran fisik keduanya tetap benar.</p><a class="button button-primary button-wide" href="{{ route('delivery-orders.pdf', $deliveryOrder) }}">▣ Lihat DO PDF</a><a class="button button-ghost button-wide" href="{{ route('delivery-orders.shipping-sticker', $deliveryOrder) }}">▣ Lihat Shipping Sticker</a>@if(auth()->user()->canAccess('delivery_orders.create'))<a class="button button-ghost button-wide" href="{{ route('delivery-orders.edit', $deliveryOrder) }}">Edit DO</a>@endif<a class="button button-ghost button-wide" href="{{ route('delivery-orders.index') }}">Kembali ke daftar</a></aside></div>
@endsection
