@extends('layouts.app')
@section('title',$role->exists?'Edit Role':'Buat Role') @section('eyebrow','ACCESS CONTROL') @section('heading',$role->exists?'Edit role':'Buat role')
@section('content')
<form method="POST" action="{{ $role->exists ? route('roles.update',$role) : route('roles.store') }}" class="panel access-form" data-role-form>@csrf @if($role->exists)@method('PUT')@endif
<div class="panel-heading"><div><p class="eyebrow">ROLE DEFINITION</p><h3>{{ $role->exists ? $role->name : 'Role baru' }}</h3></div></div>
@if($errors->any())<div class="error-box settings-error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="access-form-body"><div class="form-grid"><div class="field"><label>Nama role *</label><input name="name" value="{{ old('name',$role->name) }}" required></div><div class="field"><label>Slug *</label><input name="slug" value="{{ old('slug',$role->slug) }}" placeholder="contoh: warehouse-admin" required></div></div><div class="field"><label>Portal *</label><select name="portal" id="rolePortal"><option value="backoffice" @selected(old('portal',$role->portal)==='backoffice')>Back Office</option><option value="pos" @selected(old('portal',$role->portal)==='pos')>POS / Kasir</option></select></div><div class="field"><label>Deskripsi</label><textarea name="description" rows="3">{{ old('description',$role->description) }}</textarea></div>
<div class="permission-heading"><div><h3>Hak akses modul</h3><p>Hanya permission dari portal yang dipilih yang akan disimpan.</p></div><button type="button" class="button button-ghost" data-check-all>Pilih semua</button></div>
@foreach($permissionGroups as $portal => $modules)<div class="permission-portal" data-permission-portal="{{ $portal }}">@foreach($modules as $module => $permissions)<section><h4>{{ $module }}</h4><div class="permission-list">@foreach($permissions as $permission)<label><input type="checkbox" name="permissions[]" value="{{ $permission->id }}" @checked(in_array($permission->id,old('permissions',$role->permissions?->pluck('id')->all() ?? [])))><span>✓</span><div><strong>{{ $permission->name }}</strong><small>{{ $permission->slug }}</small></div></label>@endforeach</div></section>@endforeach</div>@endforeach
</div><div class="edit-form-actions"><a href="{{ route('roles.index') }}" class="button button-ghost">Batal</a><button class="button button-primary">Simpan role</button></div></form>
@endsection
